@namespace
class SpriteKind:
    Win = SpriteKind.create()

def on_a_pressed():
    if hero.vy == 0:
        hero.vy = -330
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

hero: Sprite = None
hero = sprites.create(img("""
        ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
    """),
    SpriteKind.player)
hero.ay = 1500
scene.camera_follow_sprite(hero)
controller.move_sprite(hero, 80, 0)
scene.set_background_color(9)
tiles.set_tilemap(tilemap("""
    level1
"""))

def on_on_update():
    if hero.vx > 0:
        hero.set_image(img("""
            ....ffffff..............
                        ..ffeeeef2f.............
                        .ffeeeef222f............
                        .feeeffeeeef............
                        .ffffee2222ef...........
                        .fe222ffffe2f...........
                        fffffffeeefff...........
                        ffe44ebf44eef...........
                        fee4d41fddef............
                        .feee4ddddf.............
                        ..fdde444ef.............
                        ..fdde22ccc.............
                        ...eef22cdc.............
                        ...f4444cddc............
                        ....fffffcddc...........
                        .....fff..cddc..........
                        ...........cdc..........
                        ............cc..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
    elif hero.vx < 0:
        hero.set_image(img("""
            ..............ffffff....
                        .............f2feeeeff..
                        ............f222feeeeff.
                        ............feeeeffeeef.
                        ...........fe2222eeffff.
                        ...........f2effff222ef.
                        ...........fffeeefffffff
                        ...........fee44fbe44eff
                        ............feddf14d4eef
                        .............fdddd4eeef.
                        .............fe444eddf..
                        .............ccc22eddf..
                        .............cdc22fee...
                        ............cddc4444f...
                        ...........cddcfffff....
                        ..........cddc..fff.....
                        ..........cdc...........
                        ..........cc............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
    else:
        hero.set_image(img("""
            ........................
                        .....ffff...............
                        ...fff22fff.............
                        ..fff2222fff............
                        .fffeeeeeefff...........
                        .ffe222222eef...........
                        .fe2ffffff2ef...........
                        .ffffeeeeffff...........
                        ffefbf44fbfeff..........
                        fee41fddf14eef..........
                        .ffffdddddeef...........
                        fddddf444eef............
                        fbbbbf2222f4e...........
                        fbbbbf2222fd4...........
                        .fccf45544f44...........
                        ..ffffffff..............
                        ....ff..ff..............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
        """))
game.on_update(on_on_update)
